services:
  art-lab-join-page-front:
    build: ./front
    container_name: art-lab-join-page-front
    restart: unless-stopped

    ports:
      - 127.0.0.1:3020:80
    depends_on:
      - art-lab-join-page-backend
    networks:
      - main

  art-lab-join-page-backend:
    build: ./back
    container_name: art-lab-join-page-backend
    restart: unless-stopped

    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - /srv/data/media:/srv/data/media
    networks:
      - main

networks:
  main:
    external: true
