services:
  art-lab-join-page:
    build: ./front
    container_name: art-lab-join-page-front
    ports:
      - 3020:80
    depends_on:
      - back

  back:
    build: ./back
    container_name: art-lab-join-page-backend
    # ports:
    #   - 8000:8000
