services:
  art-lab-join-page-front:
    build: ./front
    container_name: art-lab-join-page-front
    ports:
      - 127.0.0.1:3020:80
    depends_on:
      - art-lab-join-page-backend
    networks:
      - main

    # debug
    volumes:
      - ./front/build:/usr/share/nginx/html
      - ./front/nginx.conf:/etc/nginx/nginx.conf

  art-lab-join-page-backend:
    build: ./back
    container_name: art-lab-join-page-backend
    networks:
      - main

    # debug
    volumes:
      - ./back:/code
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade heads && uvicorn app.main:app --host 0.0.0.0 --reload"
    # command: alembic revision --autogenerate -m "init"


networks:
  main:
    external: true
