services:
  art-lab-join-page-backend:
    build: ./back
    container_name: art-lab-join-page-backend
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - /srv/data/media:/srv/data/media
      - ./back:/code
    networks:
      - main

    ports:
      - 8000:8000
    command: sh -c "alembic upgrade heads && uvicorn app.main:app --host 0.0.0.0 --reload"
    # command: alembic revision --autogenerate -m "init"


networks:
  main:
    external: true

# docker compose -f docker-compose-debug-back.yml up