"""add colums to participant forms

Revision ID: 002
Revises: 001
Create Date: 2025-03-30 11:38:54.469164

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participation_forms', sa.Column('social', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('country', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('email', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('program_example', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('time', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('participation_forms', sa.Column('raider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participation_forms', 'raider')
    op.drop_column('participation_forms', 'lang')
    op.drop_column('participation_forms', 'duration')
    op.drop_column('participation_forms', 'time')
    op.drop_column('participation_forms', 'quantity')
    op.drop_column('participation_forms', 'program_example')
    op.drop_column('participation_forms', 'email')
    op.drop_column('participation_forms', 'country')
    op.drop_column('participation_forms', 'social')
    # ### end Alembic commands ###
