"""add params to tickets

Revision ID: 007
Revises: 006
Create Date: 2025-05-14 11:50:25.564067

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participation_forms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'active')
    op.drop_column('tickets', 'phone')
    op.drop_column('participation_forms', 'deleted_at')
    # ### end Alembic commands ###
