"""add orders

Revision ID: 008
Revises: 007
Create Date: 2025-05-16 09:13:27.135614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_ids', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Add the first empty Order for tests
    from sqlalchemy.sql import table, column
    import datetime
    orders_table = table(
        'orders',
        column('id', sa.Integer),
        column('ticket_ids', sa.String),
        column('amount', sa.Integer),
        column('status', sa.String),
        column('customer', sa.String),
        column('phone', sa.String),
        column('email', sa.String),
        column('comment', sa.String),
        column('created_at', sa.DateTime(timezone=True)),
        column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(orders_table, [
        {
            'id': 1,
            'ticket_ids': '',
            'amount': 1,
            'status': 'new',
            'customer': '',
            'phone': '',
            'email': '',
            'comment': 'test',
        }
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
