name: Self-Hosted Runner Workflow

on:
    push:
        branches:
            - main

jobs:
    deploy-main:
        if: github.ref == 'refs/heads/main'
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Build and Deploy Services
              env:
                  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: |
                  docker compose up --build -d
