name: Self-Hosted Runner Workflow

on:
    push:
        branches:
            - main

jobs:
    deploy-main:
        if: github.ref == 'refs/heads/main'
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Build and Deploy Services
              env:
                  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
              run: |
                  docker compose build
                  docker compose up -d
